// Old URLs that apps, READMEs and search engines still link to.
const moved: Record<string, string> = {
  "/install/server/manual": "/install/server/source",
  "/install/connector/windows": "/install/apps/windows",
  "/install/connector/linux": "/install/apps/linux",
  "/install/connector/macos": "/install/apps/macos",
  "/install/connector/ios": "/install/apps/ios",
  "/install/connector/android": "/install/apps/android",
  "/benchmarks": "/install/benchmarks",
  "/server-stats": "/plugins/host-metrics",

  "/setup/reverse-proxy": "/configure/reverse-proxy",
  "/setup/environment-variables": "/configure/environment-variables",
  "/setup/database": "/configure/database",
  "/setup/remote-desktop": "/plugins/remote-desktop",
  "/setup/remote-sync": "/configure/desktop-sync",

  "/features/overview": "/plugins",
  "/features/authentication/overview": "/guide/account",
  "/features/authentication/sso-providers": "/plugins/sso",
  "/features/authentication/oidc": "/plugins/sso",
  "/features/authentication/github-google": "/plugins/sso",
  "/features/authentication/ldap": "/plugins/ldap",
  "/features/authentication/trusted-proxy": "/configure/trusted-proxy-login",
  "/features/authentication/totp": "/plugins/totp",
  "/features/authentication/rbac": "/guide/sharing",
  "/features/authentication/security": "/configure/security",
  "/features/authentication/opkssh": "/plugins/opkssh",
  "/features/authentication/vault": "/plugins/vault",
  "/features/authentication/termix-id": "/plugins/termix-identity",

  "/features/networking/tunnels": "/plugins/tunnels",
  "/features/networking/host-metrics": "/plugins/host-metrics",
  "/features/networking/alerts": "/plugins/alerts",
  "/features/networking/docker": "/plugins/docker",
  "/features/networking/ssl": "/configure/https",
  "/features/networking/tailscale": "/plugins/tailscale",
  "/features/networking/port-knocking": "/guide/hosts",
  "/features/networking/wake-on-lan": "/plugins/wake-on-lan",

  "/features/terminal/appearance": "/plugins/ssh-terminal",
  "/features/terminal/tmux": "/plugins/tmux-monitor",
  "/features/terminal/command-palette": "/guide/command-palette",
  "/features/terminal/snippets": "/plugins/snippets",
  "/features/terminal/macros": "/plugins/ssh-terminal",
  "/features/terminal/command-history": "/plugins/ssh-terminal",
  "/features/terminal/local-terminal": "/plugins/ssh-terminal",
  "/features/terminal/split-screen": "/guide/interface",
  "/features/terminal/session-sharing": "/plugins/session-sharing",
  "/features/terminal/session-recording": "/plugins/session-recording",

  "/features/fleets/overview": "/plugins/fleets",
  "/features/fleets/inventory": "/plugins/fleets",
  "/features/automations/overview": "/plugins/automations",
  "/features/automations/triggers": "/plugins/automations",
  "/features/automations/steps": "/plugins/automations",
  "/features/ai/overview": "/plugins/ai",
  "/features/ai/providers": "/plugins/ai",
  "/features/ai/tools": "/plugins/ai",

  "/features/files-and-hosts/proxmox-import": "/plugins/proxmox",
  "/features/files-and-hosts/credentials": "/guide/credentials",
  "/features/files-and-hosts/connection-defaults": "/guide/host-defaults",
  "/features/files-and-hosts/trash": "/plugins/file-manager",
  "/features/files-and-hosts/json-import": "/guide/import-export",
  "/features/dashboard/overview": "/guide/dashboard",
  "/features/dashboard/network-graph": "/plugins/network-topology",
  "/features/api/api-keys": "/guide/api-keys",
  "/features/workspaces": "/plugins/workspaces",

  "/api/termix-api": "/api",
};

export const redirects = Object.entries(moved).map(([from, to]) => ({
  from,
  to,
}));
