// Made by scripts/sync-content.mjs. Do not edit.
module.exports = {
  "plugin-acme-ssl": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "acme-ssl"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/acme-ssl/acme-certificates-api"
    }
  ],
  "plugin-ai": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "ai"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/ai/ai-assistant-api"
    }
  ],
  "plugin-alerts": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "alerts"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/alerts/alerts-api"
    }
  ],
  "plugin-automations": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "automations"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/automations/automations-api"
    }
  ],
  "plugin-docker": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "docker"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/docker/docker-api"
    }
  ],
  "plugin-file-manager": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "file-manager"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/file-manager/file-manager-api"
    }
  ],
  "plugin-fleets": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "fleets"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/fleets/fleets-api"
    }
  ],
  "plugin-vault": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "vault"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/vault/hashicorp-vault-api"
    }
  ],
  "plugin-homepage": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "homepage"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/homepage/homepage-api"
    }
  ],
  "plugin-host-metrics": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "host-metrics"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/host-metrics/host-metrics-api"
    }
  ],
  "plugin-ldap": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "ldap"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/ldap/ldap-api"
    }
  ],
  "plugin-network-topology": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "network-topology"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/network-topology/network-topology-api"
    }
  ],
  "plugin-opkssh": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "opkssh"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/opkssh/opkssh-api"
    }
  ],
  "plugin-webauthn": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "webauthn"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/webauthn/passkeys-api"
    }
  ],
  "plugin-proxmox": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "proxmox"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/proxmox/proxmox-api"
    }
  ],
  "plugin-remote-desktop": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "remote-desktop"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/remote-desktop/remote-desktop-api"
    }
  ],
  "plugin-secret-sources": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "secret-sources"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/secret-sources/secret-sources-api"
    }
  ],
  "plugin-serial": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "serial"
    }
  ],
  "plugin-session-recording": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "session-recording"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/session-recording/session-recording-api"
    }
  ],
  "plugin-session-sharing": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "session-sharing"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/session-sharing/session-sharing-api"
    }
  ],
  "plugin-sso": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "sso"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/sso/single-sign-on-api"
    }
  ],
  "plugin-snippets": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "snippets"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/snippets/snippets-api"
    }
  ],
  "plugin-ssh-terminal": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "ssh-terminal"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/ssh-terminal/ssh-terminal-api"
    }
  ],
  "plugin-step-ca": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "step-ca"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/step-ca/step-ca-api"
    }
  ],
  "plugin-tailscale": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "tailscale"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/tailscale/tailscale-api"
    }
  ],
  "plugin-termix-identity": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "termix-identity"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/termix-identity/termix-identity-api"
    }
  ],
  "plugin-tmux-monitor": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "tmux-monitor"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/tmux-monitor/tmux-monitor-api"
    }
  ],
  "plugin-totp": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "totp"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/totp/totp-api"
    }
  ],
  "plugin-tunnels": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "tunnels"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/tunnels/tunnels-api"
    }
  ],
  "plugin-telemetry": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "telemetry"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/telemetry/usage-statistics-api"
    }
  ],
  "plugin-wake-on-lan": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "wake-on-lan"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/wake-on-lan/wake-on-lan-api"
    }
  ],
  "plugin-warpgate": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "warpgate"
    }
  ],
  "plugin-web-endpoint": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "web-endpoint"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/web-endpoint/web-endpoint-api"
    }
  ],
  "plugin-workspaces": [
    {
      "type": "link",
      "label": "All plugins",
      "href": "/plugins"
    },
    {
      "type": "autogenerated",
      "dirName": "workspaces"
    },
    {
      "type": "link",
      "label": "API reference",
      "href": "/api/workspaces/workspaces-api"
    }
  ]
};
