import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "file-manager/file-manager-api",
    },
    {
      type: "category",
      label: "File Manager",
      items: [
        {
          type: "doc",
          id: "file-manager/list-items-in-the-hosts-termix-trash",
          label: "List items in the host's Termix trash",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/empty-the-hosts-termix-trash",
          label: "Empty the host's Termix trash",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "file-manager/restore-a-trashed-item-to-where-it-was",
          label: "Restore a trashed item to where it was",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/delete-a-trashed-item-for-good",
          label: "Delete a trashed item for good",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "file-manager/set-how-long-trashed-items-are-kept-admin-only",
          label: "Set how long trashed items are kept (admin only)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "file-manager/create-a-file",
          label: "Create a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/create-a-folder",
          label: "Create a folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/delete-a-file-or-directory",
          label: "Delete a file or directory",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "file-manager/rename-a-file-or-directory",
          label: "Rename a file or directory",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "file-manager/move-a-file-or-directory",
          label: "Move a file or directory",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "file-manager/list-files-in-a-directory",
          label: "List files in a directory",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/connect-to-ssh-for-file-management",
          label: "Connect to SSH for file management",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/verify-totp-and-complete-connection",
          label: "Verify TOTP and complete connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/continue-after-a-browser-sign-in",
          label: "Continue after a browser sign-in",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/disconnect-from-ssh",
          label: "Disconnect from SSH",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/set-sudo-password-for-session",
          label: "Set sudo password for session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/get-ssh-connection-status",
          label: "Get SSH connection status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/keep-ssh-session-alive",
          label: "Keep SSH session alive",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/extract-archive-file",
          label: "Extract archive file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/compress-files",
          label: "Compress files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/preview-how-a-host-to-host-transfer-would-run",
          label: "Preview how a host to host transfer would run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/copy-or-move-files-from-one-host-to-another",
          label: "Copy or move files from one host to another",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/list-the-callers-running-host-to-host-transfers",
          label: "List the caller's running host to host transfers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/get-a-transfers-progress",
          label: "Get a transfer's progress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/cancel-a-running-transfer",
          label: "Cancel a running transfer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/remove-the-partial-files-a-cancelled-transfer-left",
          label: "Remove the partial files a cancelled transfer left",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/retry-a-failed-or-cancelled-transfer",
          label: "Retry a failed or cancelled transfer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/download-a-file",
          label: "Download a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/stream-download-a-file",
          label: "Stream-download a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/identify-symbolic-link",
          label: "Identify symbolic link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/resolve-a-path-with-environment-variables",
          label: "Resolve a path with environment variables",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/read-a-file",
          label: "Read a file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/write-to-a-file",
          label: "Write to a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/upload-a-file",
          label: "Upload a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/stream-upload-a-file-via-multipart-form",
          label: "Stream-upload a file via multipart form",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/upload-one-raw-file-chunk",
          label: "Upload one raw file chunk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/get-recent-files",
          label: "Get recent files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/add-recent-file",
          label: "Add recent file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/remove-recent-file",
          label: "Remove recent file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "file-manager/get-pinned-files",
          label: "Get pinned files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/add-pinned-file",
          label: "Add pinned file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/remove-pinned-file",
          label: "Remove pinned file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "file-manager/get-shortcuts",
          label: "Get shortcuts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/add-shortcut",
          label: "Add shortcut",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/remove-shortcut",
          label: "Remove shortcut",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "file-manager/get-recent-transfer-destinations",
          label: "Get recent transfer destinations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "file-manager/save-a-recent-transfer-destination",
          label: "Save a recent transfer destination",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/copy-a-file-or-directory",
          label: "Copy a file or directory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/execute-a-file",
          label: "Execute a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "file-manager/change-file-permissions",
          label: "Change file permissions",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
