import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/termix-api",
    },
    {
      type: "category",
      label: "AI",
      items: [
        {
          type: "doc",
          id: "api/whether-the-ai-assistant-is-available-to-this-user",
          label: "Whether the AI assistant is available to this user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-the-users-configured-ai-providers",
          label: "List the user's configured AI providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-an-ai-provider",
          label: "Add an AI provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-an-ai-provider",
          label: "Update an AI provider",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-an-ai-provider",
          label: "Delete an AI provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-models-for-a-provider-that-has-not-been-saved-yet",
          label: "List models for a provider that has not been saved yet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-models-available-from-a-provider",
          label: "List models available from a provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-the-users-ai-conversations",
          label: "List the user's AI conversations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-one-conversation-with-its-messages-and-proposals",
          label: "Get one conversation with its messages and proposals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-a-conversation",
          label: "Delete a conversation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/send-a-message-and-stream-the-assistants-reply",
          label: "Send a message and stream the assistant's reply",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/apply-a-pending-proposal",
          label: "Apply a pending proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reject-a-pending-proposal",
          label: "Reject a pending proposal",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Alerts",
      items: [
        {
          type: "doc",
          id: "api/get-active-alerts",
          label: "Get active alerts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/dismiss-an-alert",
          label: "Dismiss an alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/undismiss-an-alert",
          label: "Undismiss an alert",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-dismissed-alerts",
          label: "Get dismissed alerts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-notification-channels-for-the-current-user",
          label: "List notification channels for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-notification-channel",
          label: "Create a notification channel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-notification-channel",
          label: "Update a notification channel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-notification-channel",
          label: "Delete a notification channel",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/send-a-test-notification",
          label: "Send a test notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-alert-rules-for-the-current-user",
          label: "List alert rules for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-an-alert-rule",
          label: "Create an alert rule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-an-alert-rule",
          label: "Update an alert rule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-an-alert-rule",
          label: "Delete an alert rule",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-alert-firings-for-the-current-user",
          label: "List alert firings for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/acknowledge-an-alert-firing",
          label: "Acknowledge an alert firing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/acknowledge-all-alert-firings-for-the-current-user",
          label: "Acknowledge all alert firings for the current user",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Credentials",
      items: [
        {
          type: "doc",
          id: "api/create-a-new-credential",
          label: "Create a new credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-credentials",
          label: "Get all credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-credential-folders",
          label: "Get credential folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-a-specific-credential",
          label: "Get a specific credential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-credential",
          label: "Update a credential",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-credential",
          label: "Delete a credential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/apply-a-credential-to-a-host",
          label: "Apply a credential to a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-hosts-using-a-credential",
          label: "Get hosts using a credential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/rename-a-credential-folder",
          label: "Rename a credential folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/detect-ssh-key-type",
          label: "Detect SSH key type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/detect-ssh-public-key-type",
          label: "Detect SSH public key type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/validate-ssh-key-pair",
          label: "Validate SSH key pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-new-ssh-key-pair",
          label: "Generate new SSH key pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-public-key-from-private-key",
          label: "Generate public key from private key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/deploy-ssh-key-to-a-host",
          label: "Deploy SSH key to a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reorder-credentials",
          label: "Reorder credentials",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Network Topology",
      items: [
        {
          type: "doc",
          id: "api/get-network-topology-for-authenticated-user",
          label: "Get network topology for authenticated user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/save-network-topology-for-authenticated-user",
          label: "Save network topology for authenticated user",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "RBAC",
      items: [
        {
          type: "doc",
          id: "api/share-a-host",
          label: "Share a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/share-all-hosts-in-a-folder",
          label: "Share all hosts in a folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-host-access-grant",
          label: "Update a host access grant",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/revoke-host-access",
          label: "Revoke host access",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-host-access-list",
          label: "Get host access list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-shared-hosts",
          label: "Get shared hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-roles",
          label: "Get all roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-new-role",
          label: "Create a new role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-role",
          label: "Update a role",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-role",
          label: "Delete a role",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-the-role-permissions-catalog",
          label: "Get the role permissions catalog",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assign-a-role-to-a-user",
          label: "Assign a role to a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-users-roles",
          label: "Get user's roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/remove-a-role-from-a-user",
          label: "Remove a role from a user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/share-a-snippet",
          label: "Share a snippet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/revoke-snippet-access",
          label: "Revoke snippet access",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-snippet-access-list",
          label: "Get snippet access list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-shared-snippets",
          label: "Get shared snippets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/set-personal-authentication-for-a-shared-host-protocol",
          label: "Set personal authentication for a shared host protocol",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-the-current-recipients-shared-host-protocol-authentication-override",
          label: "Get the current recipient's shared-host protocol authentication override",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Snippets",
      items: [
        {
          type: "doc",
          id: "api/get-all-snippet-folders",
          label: "Get all snippet folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-new-snippet-folder",
          label: "Create a new snippet folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-snippet-folder-metadata",
          label: "Update snippet folder metadata",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/rename-a-snippet-folder",
          label: "Rename a snippet folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-snippet-folder",
          label: "Delete a snippet folder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/reorder-snippets",
          label: "Reorder snippets",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/execute-a-snippet-on-a-host",
          label: "Execute a snippet on a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/export-all-snippets-and-folders-as-json",
          label: "Export all snippets and folders as JSON",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/bulk-import-snippets-and-folders-from-json",
          label: "Bulk import snippets and folders from JSON",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-snippets",
          label: "Get all snippets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-new-snippet",
          label: "Create a new snippet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-a-specific-snippet",
          label: "Get a specific snippet",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-snippet",
          label: "Update a snippet",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-snippet",
          label: "Delete a snippet",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Terminal",
      items: [
        {
          type: "doc",
          id: "api/save-command-to-history",
          label: "Save command to history",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-command-history",
          label: "Get command history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/clear-command-history",
          label: "Clear command history",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/delete-a-specific-command-from-history",
          label: "Delete a specific command from history",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-session-persistence-settings",
          label: "Get session persistence settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-session-persistence-settings",
          label: "Update session persistence settings",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "api/create-a-new-user",
          label: "Create a new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configure-oidc-provider",
          label: "Configure OIDC provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-oidc-configuration",
          label: "Disable OIDC configuration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-oidc-configuration",
          label: "Get OIDC configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-oidc-configuration-for-admin",
          label: "Get OIDC configuration for admin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-oidc-authorization-url",
          label: "Get OIDC authorization URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/oidc-callback",
          label: "OIDC callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/user-login",
          label: "User login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/user-logout",
          label: "User logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-current-users-info",
          label: "Get current user's info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/permanently-dismiss-the-donation-reminder-modal",
          label: "Permanently dismiss the donation reminder modal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-current-session-token",
          label: "Get current session token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/check-if-setup-is-required",
          label: "Check if setup is required",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/mint-a-session-for-the-sole-local-desktop-user",
          label: "Mint a session for the sole local desktop user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/count-users",
          label: "Count users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/database-health-check",
          label: "Database health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-registration-status",
          label: "Get registration status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/set-registration-status",
          label: "Set registration status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-oidc-silent-login-default-setting",
          label: "Get OIDC silent login default setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/set-oidc-silent-login-default-setting",
          label: "Set OIDC silent login default setting",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-password-login-status",
          label: "Get password login status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/set-password-login-status",
          label: "Set password login status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-password-reset-status",
          label: "Get password reset status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/set-password-reset-status",
          label: "Set password reset status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-user-account",
          label: "Delete user account",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/change-user-password",
          label: "Change user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-user-admin-only",
          label: "Delete user (admin only)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/setup-totp",
          label: "Setup TOTP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/enable-totp",
          label: "Enable TOTP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-totp",
          label: "Disable TOTP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-new-backup-codes",
          label: "Generate new backup codes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/verify-totp-during-login",
          label: "Verify TOTP during login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-guacamole-settings",
          label: "Get Guacamole settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-guacamole-settings",
          label: "Update Guacamole settings",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-log-level-setting",
          label: "Get log level setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-log-level-setting-admin-only",
          label: "Update log level setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-session-timeout-setting",
          label: "Get session timeout setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-session-timeout-setting-admin-only",
          label: "Update session timeout setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-tailscale-settings",
          label: "Get Tailscale settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-tailscale-settings-admin-only",
          label: "Update Tailscale settings (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-command-history-enabled-setting",
          label: "Get command history enabled setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-command-history-enabled-setting-admin-only",
          label: "Update command history enabled setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-analytics-enabled-setting",
          label: "Get analytics enabled setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-analytics-enabled-setting-admin-only",
          label: "Update analytics enabled setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-session-sharing-globally-enabled-setting",
          label: "Get session sharing globally enabled setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-session-sharing-globally-enabled-setting-admin-only",
          label: "Update session sharing globally enabled setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-whether-the-ai-assistant-is-enabled-instance-wide",
          label: "Get whether the AI assistant is enabled instance-wide",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-instance-wide-ai-assistant-setting-admin-only",
          label: "Update the instance-wide AI assistant setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-the-allowlist-of-private-ai-endpoint-hosts",
          label: "Get the allowlist of private AI endpoint hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/replace-the-allowlist-of-private-ai-endpoint-hosts-admin-only",
          label: "Replace the allowlist of private AI endpoint hosts (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-host-creation-defaults",
          label: "Get host creation defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-host-creation-defaults-admin-only",
          label: "Update host creation defaults (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/get-sessions",
          label: "Get sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/revoke-a-specific-session",
          label: "Revoke a specific session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/revoke-all-sessions-for-a-user",
          label: "Revoke all sessions for a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/initiate-password-reset",
          label: "Initiate password reset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/verify-reset-code",
          label: "Verify reset code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/complete-password-reset",
          label: "Complete password reset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/link-oidc-user-to-password-account",
          label: "Link OIDC user to password account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/unlink-oidc-from-password-account",
          label: "Unlink OIDC from password account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-terminal-image-storage-settings-admin-only",
          label: "Get terminal image storage settings (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-terminal-image-storage-settings-admin-only",
          label: "Update terminal image storage settings (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/test-image-storage-visibility-admin-only",
          label: "Test image storage visibility (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/unlock-user-data",
          label: "Unlock user data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/check-user-data-unlock-status",
          label: "Check user data unlock status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-users",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/make-user-admin",
          label: "Make user admin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-admin-status",
          label: "Remove admin status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/admin-create-user",
          label: "Admin create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reset-a-users-password-admin-only",
          label: "Reset a user's password (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-a-users-totp-admin-only",
          label: "Disable a user's TOTP (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/export-a-users-data-admin-only",
          label: "Export a user's data (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-acme-ssl-settings",
          label: "Get ACME SSL settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-acme-ssl-settings-admin-only",
          label: "Update ACME SSL settings (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/request-or-renew-lets-encrypt-certificate-admin-only",
          label: "Request or renew Let's Encrypt certificate (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/upload-a-manual-custom-ssl-certificate-and-key-admin-only",
          label: "Upload a manual/custom SSL certificate and key (admin only)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: [
        {
          type: "doc",
          id: "api/get-service-links",
          label: "Get service links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-service-link",
          label: "Create service link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-service-link",
          label: "Delete service link",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/update-service-link",
          label: "Update service link",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-server-uptime",
          label: "Get server uptime",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-recent-activity",
          label: "Get recent activity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/log-a-new-activity",
          label: "Log a new activity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/reset-recent-activity",
          label: "Reset recent activity",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Docker",
      items: [
        {
          type: "doc",
          id: "api/establish-ssh-session-for-docker",
          label: "Establish SSH session for Docker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disconnect-ssh-session",
          label: "Disconnect SSH session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/verify-totp-and-complete-connection",
          label: "Verify TOTP and complete connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/complete-warpgate-authentication",
          label: "Complete Warpgate authentication",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/keep-ssh-session-alive",
          label: "Keep SSH session alive",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/check-ssh-session-status",
          label: "Check SSH session status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/validate-docker-availability",
          label: "Validate Docker availability",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-all-containers",
          label: "List all containers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-container-details",
          label: "Get container details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-container",
          label: "Start container",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stop-container",
          label: "Stop container",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/restart-container",
          label: "Restart container",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/pause-container",
          label: "Pause container",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/unpause-container",
          label: "Unpause container",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-container",
          label: "Remove container",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-container-logs",
          label: "Get container logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-container-stats",
          label: "Get container stats",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "SSH Tunnels",
      items: [
        {
          type: "doc",
          id: "api/get-tunnel-status-by-name",
          label: "Get tunnel status by name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/connect-ssh-tunnel",
          label: "Connect SSH tunnel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disconnect-ssh-tunnel",
          label: "Disconnect SSH tunnel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/cancel-tunnel-retry",
          label: "Cancel tunnel retry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-tunnel-statuses",
          label: "Get all tunnel statuses",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Host Metrics",
      items: [
        {
          type: "doc",
          id: "api/update-viewer-heartbeat",
          label: "Update viewer heartbeat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/register-metrics-viewer",
          label: "Register metrics viewer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/unregister-metrics-viewer",
          label: "Unregister metrics viewer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-global-monitoring-defaults",
          label: "Get global monitoring defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-global-monitoring-defaults",
          label: "Update global monitoring defaults",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-metrics-history-retention-setting",
          label: "Get metrics history retention setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-metrics-history-retention-setting",
          label: "Update metrics history retention setting",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-the-host-metrics-layout-for-a-host",
          label: "Get the Host Metrics layout for a host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/save-the-host-metrics-layout-for-a-host",
          label: "Save the Host Metrics layout for a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-host-statuses",
          label: "Get all host statuses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-host-status-by-id",
          label: "Get host status by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/clear-all-ssh-connections",
          label: "Clear all SSH connections",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/refresh-polling",
          label: "Refresh polling",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/start-polling-for-updated-host",
          label: "Start polling for updated host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stop-polling-for-deleted-host",
          label: "Stop polling for deleted host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-host-metrics",
          label: "Get host metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-metrics-collection",
          label: "Start metrics collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stop-metrics-collection",
          label: "Stop metrics collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/complete-totp-verification-for-metrics",
          label: "Complete TOTP verification for metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-historical-metrics-for-a-host",
          label: "Get historical metrics for a host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-wire-guard-interfaces-and-peers",
          label: "Get WireGuard interfaces and peers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/bring-a-wire-guard-interface-up-or-down",
          label: "Bring a WireGuard interface up or down",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-tailscale-status-and-i-ps",
          label: "Get Tailscale status and IPs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/connect-or-disconnect-tailscale",
          label: "Connect or disconnect Tailscale",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/revoke-and-remove-an-issued-certificate-certbot-or-acme-sh",
          label: "Revoke and remove an issued certificate (certbot or acme.sh)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-systemd-services",
          label: "List systemd services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-stop-restart-enable-disable-a-systemd-service",
          label: "Start/stop/restart/enable/disable a systemd service",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-processes-rich-sortable-filterable-client-side",
          label: "List processes (rich, sortable, filterable client-side)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/send-a-signal-to-a-process-term-kill-hup-int",
          label: "Send a signal to a process (TERM/KILL/HUP/INT)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/detect-available-management-tooling-on-a-host",
          label: "Detect available management tooling on a host",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "File Manager",
      items: [
        {
          type: "doc",
          id: "api/create-a-file",
          label: "Create a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/create-a-folder",
          label: "Create a folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-a-file-or-directory",
          label: "Delete a file or directory",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/rename-a-file-or-directory",
          label: "Rename a file or directory",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/move-a-file-or-directory",
          label: "Move a file or directory",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/list-files-in-a-directory",
          label: "List files in a directory",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/connect-to-ssh-for-file-management",
          label: "Connect to SSH for file management",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/verify-totp-and-complete-connection",
          label: "Verify TOTP and complete connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/complete-warpgate-authentication",
          label: "Complete Warpgate authentication",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disconnect-from-ssh",
          label: "Disconnect from SSH",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-sudo-password-for-session",
          label: "Set sudo password for session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-ssh-connection-status",
          label: "Get SSH connection status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/keep-ssh-session-alive",
          label: "Keep SSH session alive",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/extract-archive-file",
          label: "Extract archive file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/compress-files",
          label: "Compress files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/download-a-file",
          label: "Download a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stream-download-a-file",
          label: "Stream-download a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/identify-symbolic-link",
          label: "Identify symbolic link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/resolve-a-path-with-environment-variables",
          label: "Resolve a path with environment variables",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/read-a-file",
          label: "Read a file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/write-to-a-file",
          label: "Write to a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/upload-a-file",
          label: "Upload a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stream-upload-a-file-via-multipart-form",
          label: "Stream-upload a file via multipart form",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/upload-one-raw-file-chunk",
          label: "Upload one raw file chunk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/copy-a-file-or-directory",
          label: "Copy a file or directory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/execute-a-file",
          label: "Execute a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/change-file-permissions",
          label: "Change file permissions",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SSH",
      items: [
        {
          type: "doc",
          id: "api/create-ssh-host",
          label: "Create SSH host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-ssh-hosts",
          label: "Get all SSH hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-temporary-ssh-connection-without-saving-to-database",
          label: "Create a temporary SSH connection without saving to database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-ssh-host",
          label: "Update SSH host",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-ssh-host-by-id",
          label: "Get SSH host by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-ssh-host",
          label: "Delete SSH host",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-host-password-for-clipboard-copy",
          label: "Get host password for clipboard copy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/export-ssh-host",
          label: "Export SSH host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/export-all-ssh-hosts",
          label: "Export all SSH hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-opkssh-token-status-for-a-host",
          label: "Get OPKSSH token status for a host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-opkssh-token-for-a-host",
          label: "Delete OPKSSH token for a host",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/proxy-opkssh-provider-chooser-page-and-all-related-resources",
          label: "Proxy OPKSSH provider chooser page and all related resources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/static-o-auth-callback-from-oidc-provider-for-opkssh-authentication",
          label: "Static OAuth callback from OIDC provider for OPKSSH authentication",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/o-auth-callback-from-oidc-provider-for-opkssh-authentication-handles-all-sub-paths",
          label: "OAuth callback from OIDC provider for OPKSSH authentication (handles all sub-paths)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/test-proxy-connectivity",
          label: "Test proxy connectivity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-internal-ssh-host-data",
          label: "Get internal SSH host data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-internal-ssh-host-data",
          label: "Get all internal SSH host data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/rename-folder",
          label: "Rename folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-all-folders",
          label: "Get all folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-folder-metadata",
          label: "Update folder metadata",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/reorder-folders",
          label: "Reorder folders",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-all-hosts-in-folder",
          label: "Delete all hosts in folder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-recent-files",
          label: "Get recent files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-recent-file",
          label: "Add recent file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-recent-file",
          label: "Remove recent file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-pinned-files",
          label: "Get pinned files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-pinned-file",
          label: "Add pinned file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-pinned-file",
          label: "Remove pinned file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-shortcuts",
          label: "Get shortcuts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-shortcut",
          label: "Add shortcut",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-shortcut",
          label: "Remove shortcut",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-command-history",
          label: "Get command history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-command-from-history",
          label: "Delete command from history",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/bulk-import-ssh-hosts",
          label: "Bulk import SSH hosts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/bulk-update-partial-fields-on-multiple-ssh-hosts",
          label: "Bulk update partial fields on multiple SSH hosts",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/reorder-hosts",
          label: "Reorder hosts",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/import-hosts-from-an-open-ssh-config-file",
          label: "Import hosts from an OpenSSH config file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/enable-autostart-for-ssh-configuration",
          label: "Enable autostart for SSH configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/disable-autostart-for-ssh-configuration",
          label: "Disable autostart for SSH configuration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-autostart-status",
          label: "Get autostart status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Host Enrollment",
      items: [
        {
          type: "doc",
          id: "api/enroll-a-host-with-an-api-key",
          label: "Enroll a host with an API key",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Fleets",
      items: [
        {
          type: "doc",
          id: "api/list-the-current-users-fleets",
          label: "List the current user's fleets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-fleet",
          label: "Create a fleet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-fleet",
          label: "Update a fleet",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-a-fleet",
          label: "Delete a fleet",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-the-resolved-effective-members-of-a-fleet",
          label: "List the resolved effective members of a fleet",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-a-host-to-a-fleets-static-membership",
          label: "Add a host to a fleet's static membership",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-a-host-from-a-fleets-static-membership",
          label: "Remove a host from a fleet's static membership",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/share-a-fleets-current-member-hosts-with-users-or-roles",
          label: "Share a fleet's current member hosts with users or roles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/run-a-command-across-every-host-in-a-fleet",
          label: "Run a command across every host in a fleet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/push-an-uploaded-file-to-the-same-remote-path-on-every-host-in-a-fleet",
          label: "Push an uploaded file to the same remote path on every host in a fleet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/pull-the-same-remote-path-from-every-host-in-a-fleet",
          label: "Pull the same remote path from every host in a fleet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/read-the-last-known-inventory-snapshot-for-a-fleets-members",
          label: "Read the last-known inventory snapshot for a fleet's members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/refresh-the-inventory-snapshot-for-every-host-in-a-fleet",
          label: "Refresh the inventory snapshot for every host in a fleet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/run-a-package-action-across-every-host-in-a-fleet",
          label: "Run a package action across every host in a fleet",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Workspaces",
      items: [
        {
          type: "doc",
          id: "api/list-the-current-users-saved-workspaces",
          label: "List the current user's saved workspaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/save-the-current-tab-arrangement-as-a-new-named-workspace",
          label: "Save the current tab arrangement as a new named workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/fetch-the-auto-maintained-last-session-workspace",
          label: "Fetch the auto-maintained 'Last Session' workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/upsert-the-auto-maintained-last-session-workspace",
          label: "Upsert the auto-maintained 'Last Session' workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/rename-or-recolor-a-workspace",
          label: "Rename or recolor a workspace",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-a-workspace",
          label: "Delete a workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/overwrite-a-workspaces-saved-tab-arrangement-with-a-new-payload",
          label: "Overwrite a workspace's saved tab arrangement with a new payload",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/duplicate-a-workspaces-content-and-color-icon-under-a-new-name",
          label: "Duplicate a workspace's content and color/icon under a new name",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/mark-a-workspace-as-the-restore-on-login-default",
          label: "Mark a workspace as the restore-on-login default",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-a-workspace-as-the-restore-on-login-default",
          label: "Remove a workspace as the restore-on-login default",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/fetch-a-workspace-to-apply-and-mark-it-as-just-used",
          label: "Fetch a workspace to apply and mark it as just used",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Open Tabs",
      items: [
        {
          type: "doc",
          id: "api/get-all-open-tabs-for-the-current-user",
          label: "Get all open tabs for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/upsert-a-single-open-tab-for-the-current-user",
          label: "Upsert a single open tab for the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/bulk-replace-all-open-tabs-for-the-current-user",
          label: "Bulk replace all open tabs for the current user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-a-single-open-tab",
          label: "Update a single open tab",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-a-single-open-tab",
          label: "Delete a single open tab",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-all-active-backend-sessions-for-the-current-user",
          label: "Get all active backend sessions for the current user",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Automations",
      items: [
        {
          type: "doc",
          id: "api/list-the-current-users-automations",
          label: "List the current user's automations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-an-automation",
          label: "Create an automation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/fetch-a-single-automation",
          label: "Fetch a single automation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-an-automation",
          label: "Update an automation",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-an-automation",
          label: "Delete an automation",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/run-an-automation-now",
          label: "Run an automation now",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-automation-runs",
          label: "List automation runs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/step-by-step-results-for-a-run",
          label: "Step-by-step results for a run",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/trigger-an-automation-from-an-external-system",
          label: "Trigger an automation from an external system",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Guacamole",
      items: [
        {
          type: "doc",
          id: "api/generate-an-encrypted-guacamole-connection-token",
          label: "Generate an encrypted Guacamole connection token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-guacamole-connection-token-from-host-configuration",
          label: "Generate Guacamole connection token from host configuration",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Proxmox",
      items: [
        {
          type: "doc",
          id: "api/discover-proxmox-guests-on-a-node",
          label: "Discover Proxmox guests on a node",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Proxmox Stats",
      items: [
        {
          type: "doc",
          id: "api/get-cached-proxmox-node-stats-for-a-host",
          label: "Get cached Proxmox node stats for a host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-proxmox-stats-collection",
          label: "Start Proxmox stats collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stop-proxmox-stats-collection",
          label: "Stop Proxmox stats collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-historical-proxmox-node-stats-for-a-host",
          label: "Get historical Proxmox node stats for a host",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Session Sharing",
      items: [
        {
          type: "doc",
          id: "api/create-a-session-share-link-or-targeted-user",
          label: "Create a session share (link or targeted user)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-active-session-shares-for-a-host",
          label: "List active session shares for a host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/revoke-a-session-share",
          label: "Revoke a session share",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/resolve-a-guest-share-link",
          label: "Resolve a guest share link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/end-a-shared-session-for-all-participants",
          label: "End a shared session for all participants",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Session Logs",
      items: [
        {
          type: "doc",
          id: "api/list-session-logs",
          label: "List session logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-session-log-metadata",
          label: "Get session log metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-session-log",
          label: "Delete session log",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-session-log-content",
          label: "Get session log content",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Homepage",
      items: [
        {
          type: "doc",
          id: "api/proxy-and-parse-an-rss-atom-feed",
          label: "Proxy and parse an RSS/Atom feed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/proxy-a-json-api-url-and-return-the-parsed-response",
          label: "Proxy a JSON API URL and return the parsed response",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/check-the-http-reachability-and-latency-of-a-url",
          label: "Check the HTTP reachability and latency of a URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-homepage-layout",
          label: "Get homepage layout",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/save-homepage-layout",
          label: "Save homepage layout",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-homepage-items",
          label: "Get homepage items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-homepage-item",
          label: "Create homepage item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-homepage-item",
          label: "Update homepage item",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-homepage-item",
          label: "Delete homepage item",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/proxy-favicon-fetch",
          label: "Proxy favicon fetch",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Audit",
      items: [
        {
          type: "doc",
          id: "api/list-audit-logs",
          label: "List audit logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-distinct-audit-log-action-types",
          label: "List distinct audit log action types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/export-audit-logs",
          label: "Export audit logs",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "API Keys",
      items: [
        {
          type: "doc",
          id: "api/create-an-api-key-admin-only",
          label: "Create an API key (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-all-api-keys-admin-only",
          label: "List all API keys (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-an-api-key-admin-only",
          label: "Delete an API key (admin only)",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "SSO",
      items: [
        {
          type: "doc",
          id: "api/list-enabled-sso-providers-public",
          label: "List enabled SSO providers (public)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-sso-provider",
          label: "Create SSO provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-all-sso-providers-admin",
          label: "List all SSO providers (admin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-sso-provider",
          label: "Update SSO provider",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-sso-provider",
          label: "Delete SSO provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/ldap-login",
          label: "LDAP login",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "WebAuthn",
      items: [
        {
          type: "doc",
          id: "api/list-passkeys",
          label: "List passkeys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-passkey-registration",
          label: "Start passkey registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/finish-passkey-registration",
          label: "Finish passkey registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/start-passkey-login",
          label: "Start passkey login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/finish-passkey-login",
          label: "Finish passkey login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-a-passkey",
          label: "Delete a passkey",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Vault",
      items: [
        {
          type: "doc",
          id: "api/vault-oidc-callback",
          label: "Vault OIDC callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-vault-profiles",
          label: "List Vault profiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-vault-profile",
          label: "Create a Vault profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-vault-profile",
          label: "Update a Vault profile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-vault-profile",
          label: "Delete a Vault profile",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Termix ID",
      items: [
        {
          type: "doc",
          id: "api/get-current-users-termix-id-and-keys",
          label: "Get current user's Termix ID and keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/check-if-a-handle-is-available",
          label: "Check if a handle is available",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-termix-id",
          label: "Create a Termix ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-termix-id-handle-or-description",
          label: "Update Termix ID handle or description",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-termix-id-and-all-associated-keys",
          label: "Delete Termix ID and all associated keys",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/publish-a-public-key",
          label: "Publish a public key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-a-new-key-pair-and-publish-the-public-key",
          label: "Generate a new key pair and publish the public key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-key-metadata-enabled-state-or-label",
          label: "Update key metadata (enabled state or label)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/revoke-and-delete-a-published-key",
          label: "Revoke and delete a published key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-current-users-certificate-authority",
          label: "Get current user's certificate authority",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-certificate-authority",
          label: "Create a certificate authority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-the-certificate-authority",
          label: "Delete the certificate authority",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/rotate-the-certificate-authority-revokes-all-issued-certificates",
          label: "Rotate the certificate authority (revokes all issued certificates)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/issue-an-ssh-certificate-for-a-key-ed-25519-only",
          label: "Issue an SSH certificate for a key (ed25519 only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-credential-i-ds-that-have-at-least-one-enabled-published-termix-id-key",
          label: "Get credential IDs that have at least one enabled published Termix ID key",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Tailscale",
      items: [
        {
          type: "doc",
          id: "api/list-tailscale-devices",
          label: "List Tailscale devices",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Sync",
      items: [
        {
          type: "doc",
          id: "api/pull-synced-rows-for-an-entity-type",
          label: "Pull synced rows for an entity type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/upsert-a-synced-row-by-sync-id",
          label: "Upsert a synced row by syncId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/report-a-deletion-from-the-other-side-of-a-sync-pair",
          label: "Report a deletion from the other side of a sync pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/pull-deletion-tombstones-for-an-entity-type",
          label: "Pull deletion tombstones for an entity type",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Tunnel Presets",
      items: [
        {
          type: "doc",
          id: "api/list-client-tunnel-presets",
          label: "List client tunnel presets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-a-client-tunnel-preset",
          label: "Create a client tunnel preset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-client-tunnel-preset",
          label: "Update a client tunnel preset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-client-tunnel-preset",
          label: "Delete a client tunnel preset",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "User Preferences",
      items: [
        {
          type: "doc",
          id: "api/get-preferences-for-the-current-user",
          label: "Get preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-preferences-for-the-current-user",
          label: "Update preferences for the current user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "UI Preferences",
      items: [
        {
          type: "doc",
          id: "api/get-the-ui-complexity-preferences-for-the-current-user",
          label: "Get the UI complexity preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-ui-complexity-preferences-for-the-current-user",
          label: "Update the UI complexity preferences for the current user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Host Sidebar",
      items: [
        {
          type: "doc",
          id: "api/get-the-host-sidebar-preferences-for-the-current-user",
          label: "Get the host sidebar preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-host-sidebar-preferences-for-the-current-user",
          label: "Update the host sidebar preferences for the current user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Credential Sidebar",
      items: [
        {
          type: "doc",
          id: "api/get-the-credential-sidebar-preferences-for-the-current-user",
          label: "Get the credential sidebar preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-credential-sidebar-preferences-for-the-current-user",
          label: "Update the credential sidebar preferences for the current user",
          className: "api-method put",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
