import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: 'doc',
      id: 'api/termix-api',
    },
    {
      type: 'category',
      label: 'Alerts',
      items: [
        {
          type: 'doc',
          id: 'api/get-active-alerts',
          label: 'Get active alerts',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/dismiss-an-alert',
          label: 'Dismiss an alert',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/undismiss-an-alert',
          label: 'Undismiss an alert',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-dismissed-alerts',
          label: 'Get dismissed alerts',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Credentials',
      items: [
        {
          type: 'doc',
          id: 'api/create-a-new-credential',
          label: 'Create a new credential',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-all-credentials',
          label: 'Get all credentials',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-credential-folders',
          label: 'Get credential folders',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-a-specific-credential',
          label: 'Get a specific credential',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/update-a-credential',
          label: 'Update a credential',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/delete-a-credential',
          label: 'Delete a credential',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/apply-a-credential-to-a-host',
          label: 'Apply a credential to a host',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-hosts-using-a-credential',
          label: 'Get hosts using a credential',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/rename-a-credential-folder',
          label: 'Rename a credential folder',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/detect-ssh-key-type',
          label: 'Detect SSH key type',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/detect-ssh-public-key-type',
          label: 'Detect SSH public key type',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/validate-ssh-key-pair',
          label: 'Validate SSH key pair',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/generate-new-ssh-key-pair',
          label: 'Generate new SSH key pair',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/generate-public-key-from-private-key',
          label: 'Generate public key from private key',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/deploy-ssh-key-to-a-host',
          label: 'Deploy SSH key to a host',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'Network Topology',
      items: [
        {
          type: 'doc',
          id: 'api/get-network-topology',
          label: 'Get network topology',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/save-network-topology',
          label: 'Save network topology',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'RBAC',
      items: [
        {
          type: 'doc',
          id: 'api/share-a-host',
          label: 'Share a host',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/revoke-host-access',
          label: 'Revoke host access',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-host-access-list',
          label: 'Get host access list',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-shared-hosts',
          label: 'Get shared hosts',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-all-roles',
          label: 'Get all roles',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-new-role',
          label: 'Create a new role',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/update-a-role',
          label: 'Update a role',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/delete-a-role',
          label: 'Delete a role',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/assign-a-role-to-a-user',
          label: 'Assign a role to a user',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-users-roles',
          label: "Get user's roles",
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/remove-a-role-from-a-user',
          label: 'Remove a role from a user',
          className: 'api-method delete',
        },
      ],
    },
    {
      type: 'category',
      label: 'Snippets',
      items: [
        {
          type: 'doc',
          id: 'api/get-all-snippet-folders',
          label: 'Get all snippet folders',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-new-snippet-folder',
          label: 'Create a new snippet folder',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/update-snippet-folder-metadata',
          label: 'Update snippet folder metadata',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/rename-a-snippet-folder',
          label: 'Rename a snippet folder',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/delete-a-snippet-folder',
          label: 'Delete a snippet folder',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/reorder-snippets',
          label: 'Reorder snippets',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/execute-a-snippet-on-a-host',
          label: 'Execute a snippet on a host',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-all-snippets',
          label: 'Get all snippets',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-new-snippet',
          label: 'Create a new snippet',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-a-specific-snippet',
          label: 'Get a specific snippet',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/update-a-snippet',
          label: 'Update a snippet',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/delete-a-snippet',
          label: 'Delete a snippet',
          className: 'api-method delete',
        },
      ],
    },
    {
      type: 'category',
      label: 'Terminal',
      items: [
        {
          type: 'doc',
          id: 'api/save-command-to-history',
          label: 'Save command to history',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-command-history',
          label: 'Get command history',
          className: 'api-method get',
          key: 'terminal-get-command-history',
        },
        {
          type: 'doc',
          id: 'api/clear-command-history',
          label: 'Clear command history',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/delete-a-specific-command-from-history',
          label: 'Delete a specific command from history',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'Users',
      items: [
        {
          type: 'doc',
          id: 'api/create-a-new-user',
          label: 'Create a new user',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/configure-oidc-provider',
          label: 'Configure OIDC provider',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/disable-oidc-configuration',
          label: 'Disable OIDC configuration',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-oidc-configuration',
          label: 'Get OIDC configuration',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-oidc-configuration-for-admin',
          label: 'Get OIDC configuration for admin',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-oidc-authorization-url',
          label: 'Get OIDC authorization URL',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/oidc-callback',
          label: 'OIDC callback',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/user-login',
          label: 'User login',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/user-logout',
          label: 'User logout',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-current-users-info',
          label: "Get current user's info",
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/check-if-setup-is-required',
          label: 'Check if setup is required',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/count-users',
          label: 'Count users',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/database-health-check',
          label: 'Database health check',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-registration-status',
          label: 'Get registration status',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/set-registration-status',
          label: 'Set registration status',
          className: 'api-method patch',
        },
        {
          type: 'doc',
          id: 'api/get-password-login-status',
          label: 'Get password login status',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/set-password-login-status',
          label: 'Set password login status',
          className: 'api-method patch',
        },
        {
          type: 'doc',
          id: 'api/delete-user-account',
          label: 'Delete user account',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/initiate-password-reset',
          label: 'Initiate password reset',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/verify-reset-code',
          label: 'Verify reset code',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/complete-password-reset',
          label: 'Complete password reset',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/change-user-password',
          label: 'Change user password',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/list-all-users',
          label: 'List all users',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/make-user-admin',
          label: 'Make user admin',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/remove-admin-status',
          label: 'Remove admin status',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/verify-totp-during-login',
          label: 'Verify TOTP during login',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: [
        {
          type: 'doc',
          id: 'api/get-server-uptime',
          label: 'Get server uptime',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-recent-activity',
          label: 'Get recent activity',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/log-a-new-activity',
          label: 'Log a new activity',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/reset-recent-activity',
          label: 'Reset recent activity',
          className: 'api-method delete',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docker',
      items: [
        {
          type: 'doc',
          id: 'api/establish-ssh-session-for-docker',
          label: 'Establish SSH session for Docker',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/disconnect-ssh-session',
          label: 'Disconnect SSH session',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/verify-totp-and-complete-connection',
          label: 'Verify TOTP and complete connection',
          className: 'api-method post',
          key: 'docker-verify-totp',
        },
        {
          type: 'doc',
          id: 'api/keep-ssh-session-alive',
          label: 'Keep SSH session alive',
          className: 'api-method post',
          key: 'docker-keep-alive',
        },
        {
          type: 'doc',
          id: 'api/check-ssh-session-status',
          label: 'Check SSH session status',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/validate-docker-availability',
          label: 'Validate Docker availability',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/list-all-containers',
          label: 'List all containers',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-container-details',
          label: 'Get container details',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/start-container',
          label: 'Start container',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/stop-container',
          label: 'Stop container',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/restart-container',
          label: 'Restart container',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/pause-container',
          label: 'Pause container',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/unpause-container',
          label: 'Unpause container',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/remove-container',
          label: 'Remove container',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-container-logs',
          label: 'Get container logs',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-container-stats',
          label: 'Get container stats',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'SSH Tunnels',
      items: [
        {
          type: 'doc',
          id: 'api/get-all-tunnel-statuses',
          label: 'Get all tunnel statuses',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-tunnel-status-by-name',
          label: 'Get tunnel status by name',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/connect-ssh-tunnel',
          label: 'Connect SSH tunnel',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/disconnect-ssh-tunnel',
          label: 'Disconnect SSH tunnel',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/cancel-tunnel-retry',
          label: 'Cancel tunnel retry',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'Server Stats',
      items: [
        {
          type: 'doc',
          id: 'api/get-all-host-statuses',
          label: 'Get all host statuses',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-host-status-by-id',
          label: 'Get host status by ID',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/clear-all-ssh-connections',
          label: 'Clear all SSH connections',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/refresh-polling',
          label: 'Refresh polling',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/start-polling-for-updated-host',
          label: 'Start polling for updated host',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/stop-polling-for-deleted-host',
          label: 'Stop polling for deleted host',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-host-metrics',
          label: 'Get host metrics',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/start-metrics-collection',
          label: 'Start metrics collection',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/stop-metrics-collection',
          label: 'Stop metrics collection',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/complete-totp-verification-for-metrics',
          label: 'Complete TOTP verification for metrics',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/update-viewer-heartbeat',
          label: 'Update viewer heartbeat',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/register-metrics-viewer',
          label: 'Register metrics viewer',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/unregister-metrics-viewer',
          label: 'Unregister metrics viewer',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'File Manager',
      items: [
        {
          type: 'doc',
          id: 'api/connect-to-ssh-for-file-manager',
          label: 'Connect to SSH for file manager',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/verify-totp-and-complete-connection',
          label: 'Verify TOTP and complete connection',
          className: 'api-method post',
          key: 'filemanager-verify-totp',
        },
        {
          type: 'doc',
          id: 'api/disconnect-from-ssh',
          label: 'Disconnect from SSH',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-ssh-connection-status',
          label: 'Get SSH connection status',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/keep-ssh-session-alive',
          label: 'Keep SSH session alive',
          className: 'api-method post',
          key: 'filemanager-keep-alive',
        },
        {
          type: 'doc',
          id: 'api/list-files-in-a-directory',
          label: 'List files in a directory',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/identify-symbolic-link',
          label: 'Identify symbolic link',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/read-a-file',
          label: 'Read a file',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/write-to-a-file',
          label: 'Write to a file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/upload-a-file',
          label: 'Upload a file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/create-a-file',
          label: 'Create a file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/create-a-folder',
          label: 'Create a folder',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/delete-a-file-or-directory',
          label: 'Delete a file or directory',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/rename-a-file-or-directory',
          label: 'Rename a file or directory',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/move-a-file-or-directory',
          label: 'Move a file or directory',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/download-a-file',
          label: 'Download a file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/copy-a-file-or-directory',
          label: 'Copy a file or directory',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/execute-a-file',
          label: 'Execute a file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/change-file-permissions',
          label: 'Change file permissions',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/compress-files',
          label: 'Compress files',
          className: 'api-method post',
        },
      ],
    },
    {
      type: 'category',
      label: 'SSH',
      items: [
        {
          type: 'doc',
          id: 'api/get-internal-ssh-host-data',
          label: 'Get internal SSH host data',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-all-internal-ssh-host-data',
          label: 'Get all internal SSH host data',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-ssh-host',
          label: 'Create SSH host',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-all-ssh-hosts',
          label: 'Get all SSH hosts',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/update-ssh-host',
          label: 'Update SSH host',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/get-ssh-host-by-id',
          label: 'Get SSH host by ID',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/delete-ssh-host',
          label: 'Delete SSH host',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/export-ssh-host',
          label: 'Export SSH host',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-recent-files',
          label: 'Get recent files',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/add-recent-file',
          label: 'Add recent file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/remove-recent-file',
          label: 'Remove recent file',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-pinned-files',
          label: 'Get pinned files',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/add-pinned-file',
          label: 'Add pinned file',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/remove-pinned-file',
          label: 'Remove pinned file',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-shortcuts',
          label: 'Get shortcuts',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/add-shortcut',
          label: 'Add shortcut',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/remove-shortcut',
          label: 'Remove shortcut',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-command-history',
          label: 'Get command history',
          className: 'api-method get',
          key: 'ssh-get-command-history',
        },
        {
          type: 'doc',
          id: 'api/delete-command-from-history',
          label: 'Delete command from history',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/rename-folder',
          label: 'Rename folder',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/get-all-folders',
          label: 'Get all folders',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/update-folder-metadata',
          label: 'Update folder metadata',
          className: 'api-method put',
        },
        {
          type: 'doc',
          id: 'api/delete-all-hosts-in-folder',
          label: 'Delete all hosts in folder',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/bulk-import-ssh-hosts',
          label: 'Bulk import SSH hosts',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/enable-autostart-for-ssh-configuration',
          label: 'Enable autostart for SSH configuration',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/disable-autostart-for-ssh-configuration',
          label: 'Disable autostart for SSH configuration',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'api/get-autostart-status',
          label: 'Get autostart status',
          className: 'api-method get',
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
