import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "core/termix-api",
    },
    {
      type: "category",
      label: "Auth",
      items: [
        {
          type: "doc",
          id: "core/list-login-methods",
          label: "List login methods",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/start-a-second-factor",
          label: "Start a second factor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/finish-a-second-factor",
          label: "Finish a second factor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/finish-a-login-with-a-second-factor-2-8-route",
          label: "Finish a login with a second factor (2.8 route)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/start-a-redirect-login",
          label: "Start a redirect login",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/redirect-login-callback",
          label: "Redirect login callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/redirect-login-callback-form-post",
          label: "Redirect login callback (form post)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/form-login",
          label: "Form login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/start-a-redirect-login-2-8-route",
          label: "Start a redirect login (2.8 route)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-sign-in-providers-2-8-route",
          label: "List sign-in providers (2.8 route)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/form-login-2-8-route",
          label: "Form login (2.8 route)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "core/create-a-new-user",
          label: "Create a new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/trusted-proxy-login",
          label: "Trusted proxy login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/user-login",
          label: "User login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/user-logout",
          label: "User logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-current-users-info",
          label: "Get current user's info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/permanently-dismiss-the-donation-reminder-modal",
          label: "Permanently dismiss the donation reminder modal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-current-session-token",
          label: "Get current session token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/check-if-setup-is-required",
          label: "Check if setup is required",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/mint-a-session-for-the-sole-local-desktop-user",
          label: "Mint a session for the sole local desktop user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/count-users",
          label: "Count users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/database-health-check",
          label: "Database health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-registration-status",
          label: "Get registration status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/set-registration-status",
          label: "Set registration status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-the-external-account-auto-create-setting",
          label: "Get the external account auto-create setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/set-the-external-account-auto-create-setting",
          label: "Set the external account auto-create setting",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-the-external-login-second-factor-setting",
          label: "Get the external-login second-factor setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/set-the-external-login-second-factor-setting",
          label: "Set the external-login second-factor setting",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-password-login-status",
          label: "Get password login status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/set-password-login-status",
          label: "Set password login status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-password-reset-status",
          label: "Get password reset status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/set-password-reset-status",
          label: "Set password reset status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/delete-user-account",
          label: "Delete user account",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/change-user-password",
          label: "Change user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/delete-user-admin-only",
          label: "Delete user (admin only)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/get-log-level-setting",
          label: "Get log level setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-log-level-setting-admin-only",
          label: "Update log level setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-session-timeout-setting",
          label: "Get session timeout setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-session-timeout-setting-admin-only",
          label: "Update session timeout setting (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-audit-log-forwarding-settings-admin-only",
          label: "Get audit log forwarding settings (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-audit-log-forwarding-settings-admin-only",
          label: "Update audit log forwarding settings (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-the-private-hosts-notification-channels-may-contact-admin-only",
          label: "Get the private hosts notification channels may contact (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/replace-that-allowlist-admin-only",
          label: "Replace that allowlist (admin only)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/get-sessions",
          label: "Get sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/revoke-a-specific-session",
          label: "Revoke a specific session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/revoke-all-sessions-for-a-user",
          label: "Revoke all sessions for a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/initiate-password-reset",
          label: "Initiate password reset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/verify-reset-code",
          label: "Verify reset code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/complete-password-reset",
          label: "Complete password reset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/merge-an-external-account-into-a-password-account",
          label: "Merge an external account into a password account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/remove-external-sign-in-from-a-password-account",
          label: "Remove external sign-in from a password account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/unlock-user-data",
          label: "Unlock user data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/check-user-data-unlock-status",
          label: "Check user data unlock status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-users",
          label: "List users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/make-user-admin",
          label: "Make user admin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/remove-admin-status",
          label: "Remove admin status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/admin-create-user",
          label: "Admin create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/reset-a-users-password-admin-only",
          label: "Reset a user's password (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/list-a-users-second-factors-admin-only",
          label: "List a user's second factors (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/reset-a-users-second-factors-admin-only",
          label: "Reset a user's second factors (admin only)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/export-a-users-data-admin-only",
          label: "Export a user's data (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-the-served-tls-certificate-admin-only",
          label: "Get the served TLS certificate (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/upload-a-tls-certificate-and-key-admin-only",
          label: "Upload a TLS certificate and key (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-white-label-branding",
          label: "Get white-label branding",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-white-label-branding-admin-only",
          label: "Update white-label branding (admin only)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "API Keys",
      items: [
        {
          type: "doc",
          id: "core/create-an-api-key-admin-only",
          label: "Create an API key (admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/list-all-api-keys-admin-only",
          label: "List all API keys (admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/delete-an-api-key-admin-only",
          label: "Delete an API key (admin only)",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Encryption",
      items: [
        {
          type: "doc",
          id: "core/get-encryption-status",
          label: "Get encryption status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/initialize-security-system",
          label: "Initialize security system",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/regenerate-jwt-secret",
          label: "Regenerate JWT secret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/regenerate-jwt-secret",
          label: "Regenerate JWT secret",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SSH",
      items: [
        {
          type: "doc",
          id: "core/create-ssh-host",
          label: "Create SSH host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-all-ssh-hosts",
          label: "Get all SSH hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/create-a-temporary-ssh-connection-without-saving-to-database",
          label: "Create a temporary SSH connection without saving to database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/update-ssh-host",
          label: "Update SSH host",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-ssh-host-by-id",
          label: "Get SSH host by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/delete-ssh-host",
          label: "Delete SSH host",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/get-the-login-a-desktop-needs-to-reach-a-shared-host-itself",
          label: "Get the login a desktop needs to reach a shared host itself",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-host-password-for-clipboard-copy",
          label: "Get host password for clipboard copy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/export-ssh-host",
          label: "Export SSH host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/export-all-ssh-hosts",
          label: "Export all SSH hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-the-predefined-host-tags",
          label: "Get the predefined host tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/replace-the-predefined-host-tags",
          label: "Replace the predefined host tags",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-host-statuses",
          label: "Get host statuses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-status-check-settings",
          label: "Get status check settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-status-check-settings",
          label: "Update status check settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/restart-status-checks",
          label: "Restart status checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-one-hosts-status",
          label: "Get one host's status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/test-proxy-connectivity",
          label: "Test proxy connectivity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/rename-folder",
          label: "Rename folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-all-folders",
          label: "Get all folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-folder-metadata",
          label: "Update folder metadata",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/reorder-folders",
          label: "Reorder folders",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/delete-all-hosts-in-folder",
          label: "Delete all hosts in folder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/bulk-import-ssh-hosts",
          label: "Bulk import SSH hosts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/bulk-update-partial-fields-on-multiple-ssh-hosts",
          label: "Bulk update partial fields on multiple SSH hosts",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/reorder-hosts",
          label: "Reorder hosts",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/import-hosts-from-an-open-ssh-config-file",
          label: "Import hosts from an OpenSSH config file",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SSH Auth",
      items: [
        {
          type: "doc",
          id: "core/list-ssh-auth-types",
          label: "List SSH auth types",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Host Defaults",
      items: [
        {
          type: "doc",
          id: "core/get-the-servers-host-defaults",
          label: "Get the server's host defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-the-servers-host-defaults",
          label: "Update the server's host defaults",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-your-host-defaults",
          label: "Get your host defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-your-host-defaults",
          label: "Update your host defaults",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-a-folders-host-defaults",
          label: "Get a folder's host defaults",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-a-folders-host-defaults",
          label: "Update a folder's host defaults",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-or-create-a-folders-defaults-id",
          label: "Get or create a folder's defaults id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/preview-a-host-defaults-change",
          label: "Preview a host defaults change",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/resolve-host-defaults-for-a-host",
          label: "Resolve host defaults for a host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/host-defaults-job-status",
          label: "Host defaults job status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/reset-a-host-to-its-defaults",
          label: "Reset a host to its defaults",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Host Enrollment",
      items: [
        {
          type: "doc",
          id: "core/enroll-a-host-with-an-api-key",
          label: "Enroll a host with an API key",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Credentials",
      items: [
        {
          type: "doc",
          id: "core/create-a-new-credential",
          label: "Create a new credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-all-credentials",
          label: "Get all credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-credential-folders",
          label: "Get credential folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-a-specific-credential",
          label: "Get a specific credential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-a-credential",
          label: "Update a credential",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/delete-a-credential",
          label: "Delete a credential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/duplicate-a-credential",
          label: "Duplicate a credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/apply-a-credential-to-a-host",
          label: "Apply a credential to a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-hosts-using-a-credential",
          label: "Get hosts using a credential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/rename-a-credential-folder",
          label: "Rename a credential folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/detect-ssh-key-type",
          label: "Detect SSH key type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/detect-ssh-public-key-type",
          label: "Detect SSH public key type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/validate-ssh-key-pair",
          label: "Validate SSH key pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/generate-new-ssh-key-pair",
          label: "Generate new SSH key pair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/generate-public-key-from-private-key",
          label: "Generate public key from private key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/deploy-ssh-key-to-a-host",
          label: "Deploy SSH key to a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/reorder-credentials",
          label: "Reorder credentials",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "RBAC",
      items: [
        {
          type: "doc",
          id: "core/share-a-host",
          label: "Share a host",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/share-all-hosts-in-a-folder",
          label: "Share all hosts in a folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/change-a-host-access-rule",
          label: "Change a host access rule",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/revoke-host-access",
          label: "Revoke host access",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/standing-shares-on-one-of-your-folders-inherited-by-hosts-added-later",
          label: "Standing shares on one of your folders (inherited by hosts added later)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/stop-a-folder-share-from-applying-to-hosts-added-later",
          label: "Stop a folder share from applying to hosts added later",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/get-host-access-list",
          label: "Get host access list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-shared-hosts",
          label: "Get shared hosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-all-roles",
          label: "Get all roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/create-a-new-role",
          label: "Create a new role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/update-a-role",
          label: "Update a role",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/delete-a-role",
          label: "Delete a role",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/get-the-role-permissions-catalog",
          label: "Get the role permissions catalog",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-the-current-users-effective-role-permissions",
          label: "Get the current user's effective role permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-the-users-holding-a-role",
          label: "List the users holding a role",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/assign-a-role-to-a-user",
          label: "Assign a role to a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-users-roles",
          label: "Get user's roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/remove-a-role-from-a-user",
          label: "Remove a role from a user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/share-a-credential-with-users-or-roles",
          label: "Share a credential with users or roles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/list-who-a-credential-is-shared-with",
          label: "List who a credential is shared with",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/revoke-a-credential-share-recipients-copies-are-removed-with-it",
          label: "Revoke a credential share (recipients' copies are removed with it)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/set-personal-authentication-for-a-shared-host-protocol",
          label: "Set personal authentication for a shared host protocol",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-the-current-recipients-shared-host-protocol-authentication-override",
          label: "Get the current recipient's shared-host protocol authentication override",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: [
        {
          type: "doc",
          id: "core/get-server-uptime",
          label: "Get server uptime",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-recent-activity",
          label: "Get recent activity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/log-a-new-activity",
          label: "Log a new activity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/reset-recent-activity",
          label: "Reset recent activity",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Audit",
      items: [
        {
          type: "doc",
          id: "core/list-audit-logs",
          label: "List audit logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-distinct-audit-log-action-types",
          label: "List distinct audit log action types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/export-audit-logs",
          label: "Export audit logs",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Plugins",
      items: [
        {
          type: "doc",
          id: "core/serve-a-plugins-frontend-bundle-stylesheet-or-locale-file",
          label: "Serve a plugin's frontend bundle, stylesheet or locale file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-the-plugin-frontends-anonymous-guest-pages-need",
          label: "List the plugin frontends anonymous guest pages need",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-the-plugin-frontends-the-login-screen-needs",
          label: "List the plugin frontends the login screen needs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-installed-plugins-and-their-runtime-state",
          label: "List installed plugins and their runtime state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/list-plugins-for-the-onboarding-plugin-picker",
          label: "List plugins for the onboarding plugin picker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/apply-the-onboarding-plugin-picker",
          label: "Apply the onboarding plugin picker",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/enable-or-disable-a-plugin",
          label: "Enable or disable a plugin",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/start-a-plugin-again-after-it-failed",
          label: "Start a plugin again after it failed",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/grant-a-plugin-one-of-its-manifest-declared-capabilities",
          label: "Grant a plugin one of its manifest-declared capabilities",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/revoke-a-previously-granted-plugin-capability",
          label: "Revoke a previously granted plugin capability",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/delete-everything-a-plugin-stores",
          label: "Delete everything a plugin stores",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/summarize-what-a-plugin-stores",
          label: "Summarize what a plugin stores",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/read-a-plugins-install-wide-settings",
          label: "Read a plugin's install-wide settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-a-plugins-install-wide-settings",
          label: "Update a plugin's install-wide settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/read-the-callers-own-settings-for-a-plugin",
          label: "Read the caller's own settings for a plugin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-the-callers-own-settings-for-a-plugin",
          label: "Update the caller's own settings for a plugin",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/read-a-plugins-settings-for-one-host",
          label: "Read a plugin's settings for one host",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-a-plugins-settings-for-one-host",
          label: "Update a plugin's settings for one host",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/list-the-plugins-in-the-official-registry",
          label: "List the plugins in the official registry",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-every-plugin-that-has-a-newer-release",
          label: "Update every plugin that has a newer release",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/move-every-installed-plugin-to-one-update-channel",
          label: "Move every installed plugin to one update channel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/install-a-plugin-from-the-official-registry",
          label: "Install a plugin from the official registry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/update-or-change-the-installed-version-of-a-plugin",
          label: "Update or change the installed version of a plugin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/uninstall-a-plugin",
          label: "Uninstall a plugin",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/change-a-plugins-update-choices",
          label: "Change a plugin's update choices",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/read-an-installed-plugins-release-notes",
          label: "Read an installed plugin's release notes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/read-whether-plugin-developer-mode-is-on",
          label: "Read whether plugin developer mode is on",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/turn-plugin-developer-mode-on-or-off",
          label: "Turn plugin developer mode on or off",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/upload-a-tmxplug-to-install-from-a-file",
          label: "Upload a .tmxplug to install from a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/install-a-plugin-uploaded-from-a-file",
          label: "Install a plugin uploaded from a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/dispatch-a-request-to-an-installed-plugins-backend-router",
          label: "Dispatch a request to an installed plugin's backend router",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Sync",
      items: [
        {
          type: "doc",
          id: "core/describe-this-server-to-a-desktop-that-wants-to-link-to-it",
          label: "Describe this server to a desktop that wants to link to it",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/link-a-desktop-to-this-account",
          label: "Link a desktop to this account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/keep-a-linked-desktops-session-from-expiring",
          label: "Keep a linked desktop's session from expiring",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/end-a-linked-desktops-session",
          label: "End a linked desktop's session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/pull-what-changed-for-this-account-after-a-cursor",
          label: "Pull what changed for this account after a cursor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/push-a-desktops-changes",
          label: "Push a desktop's changes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/stream-a-notice-whenever-this-accounts-data-changes",
          label: "Stream a notice whenever this account's data changes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/this-servers-id-for-a-host-by-its-sync-id",
          label: "This server's id for a host, by its sync id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/status-of-the-hosts-this-account-can-see-keyed-by-sync-id",
          label: "Status of the hosts this account can see, keyed by sync id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/the-features-this-server-runs-for-a-linked-desktop-to-mirror",
          label: "The features this server runs, for a linked desktop to mirror",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/download-an-installed-plugin-so-a-linked-desktop-can-install-it",
          label: "Download an installed plugin so a linked desktop can install it",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/this-desktops-link-to-a-server",
          label: "This desktop's link to a server",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/check-a-server-address-before-linking",
          label: "Check a server address before linking",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/how-much-this-desktop-has-that-would-sync",
          label: "How much this desktop has that would sync",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/link-this-desktop-to-a-server-account",
          label: "Link this desktop to a server account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/sign-this-desktop-back-in-after-its-session-ended",
          label: "Sign this desktop back in after its session ended",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/unlink-this-desktop-from-its-server",
          label: "Unlink this desktop from its server",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/sync-now",
          label: "Sync now",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/change-what-syncs-and-how-the-server-is-reached",
          label: "Change what syncs and how the server is reached",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/local-edits-that-lost-to-a-newer-edit-on-the-server",
          label: "Local edits that lost to a newer edit on the server",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/settle-a-conflict",
          label: "Settle a conflict",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/changes-the-server-refused",
          label: "Changes the server refused",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/send-refused-changes-again",
          label: "Send refused changes again",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/the-linked-server-and-session-for-connecting-to-it-directly",
          label: "The linked server and session, for connecting to it directly",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Database",
      items: [
        {
          type: "doc",
          id: "core/export-user-data",
          label: "Export user data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/import-user-data",
          label: "Import user data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/preview-user-data-export",
          label: "Preview user data export",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/restore-database-from-backup",
          label: "Restore database from backup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/get-database-migration-status",
          label: "Get database migration status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-database-migration-history",
          label: "Get database migration history",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "General",
      items: [
        {
          type: "doc",
          id: "core/health-check",
          label: "Health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/answer-an-acme-http-01-challenge",
          label: "Answer an ACME http-01 challenge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-version-information",
          label: "Get version information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-the-update-channel",
          label: "Get the update channel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/set-the-update-channel",
          label: "Set the update channel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/get-the-newest-stable-and-beta-releases",
          label: "Get the newest stable and beta releases",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-releases-in-rss-format",
          label: "Get releases in RSS format",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Open Tabs",
      items: [
        {
          type: "doc",
          id: "core/get-all-open-tabs-for-the-current-user",
          label: "Get all open tabs for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/upsert-a-single-open-tab-for-the-current-user",
          label: "Upsert a single open tab for the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/bulk-replace-all-open-tabs-for-the-current-user",
          label: "Bulk replace all open tabs for the current user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/update-a-single-open-tab",
          label: "Update a single open tab",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "core/delete-a-single-open-tab",
          label: "Delete a single open tab",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/get-how-long-a-detached-session-is-kept",
          label: "Get how long a detached session is kept",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/get-all-active-backend-sessions-for-the-current-user",
          label: "Get all active backend sessions for the current user",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "User Preferences",
      items: [
        {
          type: "doc",
          id: "core/get-preferences-for-the-current-user",
          label: "Get preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-preferences-for-the-current-user",
          label: "Update preferences for the current user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "UI Preferences",
      items: [
        {
          type: "doc",
          id: "core/get-the-ui-complexity-preferences-for-the-current-user",
          label: "Get the UI complexity preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-the-ui-complexity-preferences-for-the-current-user",
          label: "Update the UI complexity preferences for the current user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Host Sidebar",
      items: [
        {
          type: "doc",
          id: "core/get-the-host-sidebar-preferences-for-the-current-user",
          label: "Get the host sidebar preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-the-host-sidebar-preferences-for-the-current-user",
          label: "Update the host sidebar preferences for the current user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Credential Sidebar",
      items: [
        {
          type: "doc",
          id: "core/get-the-credential-sidebar-preferences-for-the-current-user",
          label: "Get the credential sidebar preferences for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/update-the-credential-sidebar-preferences-for-the-current-user",
          label: "Update the credential sidebar preferences for the current user",
          className: "api-method put",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
